# GitHub Actions workflow for Azure Web App Deployment

name: Python Web App Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to Azure
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build Docker image
      run: |
        docker build -t simple-web-app:latest .

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "ecommerce-webapp"  # Replace with your Azure Web App name
        slot-name: "production"
        package: .
